version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  build-then-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
workflows:
  build-then-test:
    jobs:
      - build-then-test
